// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using casus_oyunu.Data;

#nullable disable

namespace casus_oyunu.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250731114141_asddsacvcvc")]
    partial class asddsacvcvc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("casus_oyunu.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameRoomId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SenderParticipantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GameRoomId");

                    b.HasIndex("SenderParticipantId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("casus_oyunu.Models.GameRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("SelectedCategories")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SelectedDuration")
                        .HasColumnType("int");

                    b.Property<string>("SelectedWords")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("GameRooms");
                });

            modelBuilder.Entity("casus_oyunu.Models.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CurrentAnswererId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CurrentQuestionerId")
                        .HasColumnType("int");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("GameFinished")
                        .HasColumnType("bit");

                    b.Property<int>("GameRoomId")
                        .HasColumnType("int");

                    b.Property<int?>("GameRoomId1")
                        .HasColumnType("int");

                    b.Property<int?>("SpyParticipantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("VotingEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Winner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameRoomId");

                    b.HasIndex("GameRoomId1");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("casus_oyunu.Models.GameState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("FinishMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Finished")
                        .HasColumnType("bit");

                    b.Property<int>("GameRoomId")
                        .HasColumnType("int");

                    b.Property<string>("SelectedWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpyParticipantId")
                        .HasColumnType("int");

                    b.Property<bool>("Started")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GameRoomId");

                    b.ToTable("GameStates");
                });

            modelBuilder.Entity("casus_oyunu.Models.PlayerPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomParticipantId")
                        .HasColumnType("int");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("RoomParticipantId");

                    b.ToTable("PlayerPositions");
                });

            modelBuilder.Entity("casus_oyunu.Models.PlayerRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSpy")
                        .HasColumnType("bit");

                    b.Property<int>("RoomParticipantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomParticipantId");

                    b.ToTable("PlayerRoles");
                });

            modelBuilder.Entity("casus_oyunu.Models.RoomParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameRoomId")
                        .HasColumnType("int");

                    b.Property<int?>("GameRoomId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameRoomId");

                    b.HasIndex("GameRoomId1");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("RoomParticipants");
                });

            modelBuilder.Entity("casus_oyunu.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("casus_oyunu.Models.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubscription");
                });

            modelBuilder.Entity("casus_oyunu.Models.UserTheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThemeType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserTheme");
                });

            modelBuilder.Entity("casus_oyunu.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameRoomId")
                        .HasColumnType("int");

                    b.Property<int>("TargetParticipantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VoterParticipantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameRoomId");

                    b.HasIndex("TargetParticipantId");

                    b.HasIndex("VoterParticipantId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("casus_oyunu.Models.ChatMessage", b =>
                {
                    b.HasOne("casus_oyunu.Models.GameRoom", "GameRoom")
                        .WithMany("ChatMessages")
                        .HasForeignKey("GameRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("casus_oyunu.Models.RoomParticipant", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameRoom");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("casus_oyunu.Models.GameRoom", b =>
                {
                    b.HasOne("casus_oyunu.Models.User", "Creator")
                        .WithMany("CreatedRooms")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("casus_oyunu.Models.GameSession", b =>
                {
                    b.HasOne("casus_oyunu.Models.GameRoom", "GameRoom")
                        .WithMany()
                        .HasForeignKey("GameRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("casus_oyunu.Models.GameRoom", null)
                        .WithMany("GameSessions")
                        .HasForeignKey("GameRoomId1");

                    b.Navigation("GameRoom");
                });

            modelBuilder.Entity("casus_oyunu.Models.GameState", b =>
                {
                    b.HasOne("casus_oyunu.Models.GameRoom", "GameRoom")
                        .WithMany("GameStates")
                        .HasForeignKey("GameRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameRoom");
                });

            modelBuilder.Entity("casus_oyunu.Models.PlayerPosition", b =>
                {
                    b.HasOne("casus_oyunu.Models.RoomParticipant", "RoomParticipant")
                        .WithMany()
                        .HasForeignKey("RoomParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomParticipant");
                });

            modelBuilder.Entity("casus_oyunu.Models.PlayerRole", b =>
                {
                    b.HasOne("casus_oyunu.Models.RoomParticipant", "RoomParticipant")
                        .WithMany()
                        .HasForeignKey("RoomParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomParticipant");
                });

            modelBuilder.Entity("casus_oyunu.Models.RoomParticipant", b =>
                {
                    b.HasOne("casus_oyunu.Models.GameRoom", "GameRoom")
                        .WithMany()
                        .HasForeignKey("GameRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("casus_oyunu.Models.GameRoom", null)
                        .WithMany("RoomParticipants")
                        .HasForeignKey("GameRoomId1");

                    b.HasOne("casus_oyunu.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("casus_oyunu.Models.User", null)
                        .WithMany("RoomParticipants")
                        .HasForeignKey("UserId1");

                    b.Navigation("GameRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("casus_oyunu.Models.UserSubscription", b =>
                {
                    b.HasOne("casus_oyunu.Models.User", "User")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("casus_oyunu.Models.UserTheme", b =>
                {
                    b.HasOne("casus_oyunu.Models.User", "User")
                        .WithOne("UserTheme")
                        .HasForeignKey("casus_oyunu.Models.UserTheme", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("casus_oyunu.Models.Vote", b =>
                {
                    b.HasOne("casus_oyunu.Models.GameRoom", "GameRoom")
                        .WithMany("Votes")
                        .HasForeignKey("GameRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("casus_oyunu.Models.RoomParticipant", "Target")
                        .WithMany()
                        .HasForeignKey("TargetParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("casus_oyunu.Models.RoomParticipant", "Voter")
                        .WithMany()
                        .HasForeignKey("VoterParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameRoom");

                    b.Navigation("Target");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("casus_oyunu.Models.GameRoom", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("GameSessions");

                    b.Navigation("GameStates");

                    b.Navigation("RoomParticipants");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("casus_oyunu.Models.User", b =>
                {
                    b.Navigation("CreatedRooms");

                    b.Navigation("RoomParticipants");

                    b.Navigation("UserSubscriptions");

                    b.Navigation("UserTheme");
                });
#pragma warning restore 612, 618
        }
    }
}
